# Plugin prefix!
Prefix: '&7[ &a&lCSL&c&l+ &7]&f ➟&r '

# Which lang file that you want to use, you can name it whatever you want to. Btw
# make sure To make one just copy and paste the whole lang.yml file and
# rename it, make sure you don't edit any of the config keys, by default it will make a EN_lang file if no lang file found
# WARNING it will throw an error and disabled the plugin if the <name>.yml file is not found!
Language: 'EN_lang' # + yml

# Set this to true if you want to decrease the shopCreated value on player's data on ShopRemove. The refunded value will always be 1
RefundOnShopRemove: true
# Set this to true if you want to make a player that has unlimited shop permission to get a refund when he/she break the shop
RefundOnShopRemove-Unlimited: false

# This is all the dependency things for the plugin. If it enabled the plugin will try to hook to that plugin.
#
Dependency:
  LuckPerms: true
  # For Essentials and CMI you can only enable 1. So choose it wisely
  Essentials: false
  CMI: true

# If this enabled, the plugin will collect some information about the server. If you don't want it to happens you can set this to 'false'
# it is recommended to not set it to false because it helps the dev to improve the plugin and know how much server using the plugin
use-bstats: true

# This is the sound of "success" and "failure" when using a command. Required to reload / restart the server if you made changes
# for the sound list, you can see it here https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
CommandSound:
  success:
    volume: 10
    pitch: 0
    sound: BLOCK_NOTE_BLOCK_PLING
  failure:
    volume: 10
    pitch: 1
    sound: ENTITY_BLAZE_DEATH

# If this enabled
# Now'll explain you how the limit works. Sorry 4 my bad english
# Shop limit will be needed if the player that is checked didn't have the csl.limit.unlimited permission.
ShopLimit:
  # You can name it whatever you want to. The permission will be csl.limit.<name>
  # It is recommended to have the limit below 10, because it will create lags when the player join the server for the first time, when the plugin installed
  # Btw DO NOT delete the default key if the 'force-default' is enabled!
  default:
    limit: 5
  vip:
    limit: 10
  mvp:
    limit: 20
  # This will be needed to set to true if you want to make the player use the default limit if they don't have any permission for shop limit (csl.limit.<name>)
  force-default: true

# Will be used if you have Dependency.LuckPerms enabled!.
# WARNING PLEASE READ ALL OF THE COMMENT BELOW IF YOU WANT TO USE LuckPerms SUPPORT!
ShopLimitLuckperms:

  # Please name it exactly the SAME name on the luckperms group!
  # You can rename this, I use iron, gold, diamond because that is the group that I use for my test server
  # so you may ask how this thing work. Well its simple, it just check what group that the player is on. And then set the limit for it,
  # simple as that. You don't need other permission things for this
  iron:
    limit: 10
  gold:
    limit: 20
  diamond:
    limit: 30
